# Generated by Django 5.2.4 on 2025-08-02 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Введите ФИО сотрудника",
                        max_length=255,
                        verbose_name="ФИО",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="Укажите должность",
                        max_length=100,
                        verbose_name="Должность",
                    ),
                ),
                (
                    "competence_level",
                    models.CharField(
                        help_text="Уровень квалификации (например: junior, middle, senior)",
                        max_length=50,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Укажите почту",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Введите номер телефона",
                        max_length=15,
                        verbose_name="Телефон",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Поставьте задачу",
                        max_length=255,
                        verbose_name="Задача",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Опишите задачу подробнее (если требуется)",
                        null=True,
                        verbose_name="Описание задачи",
                    ),
                ),
                ("deadline", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "Ожидает начала"),
                            ("in_progress", "В работе"),
                            ("done", "Выполнена"),
                            ("rework", "На доработке"),
                        ],
                        default="todo",
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="attachments/"),
                ),
                ("notify_email", models.BooleanField(default=True)),
                ("notify_phone", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "executor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="task_tracker.employee",
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subtasks",
                        to="task_tracker.task",
                    ),
                ),
            ],
        ),
    ]
