# Generated by Django 5.2.4 on 2025-08-02 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_tracker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="notify_phone",
        ),
        migrations.AddField(
            model_name="task",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("easy", "Простая"),
                    ("medium", "Средняя"),
                    ("hard", "Сложная"),
                ],
                default="easy",
                help_text="Укажите уровень сложности",
                max_length=10,
                verbose_name="Уровень сложности задачи",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="competence_level",
            field=models.CharField(
                choices=[
                    ("junior", "Junior"),
                    ("middle", "Middle"),
                    ("senior", "Senior"),
                ],
                help_text="Уровень квалификации (например: junior, middle, senior)",
                max_length=50,
                verbose_name="Уровень квалификации",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Прикрепите файл при необходимости",
                null=True,
                upload_to="attachments/",
                verbose_name="Вложение",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Укажите доп.информацию",
                verbose_name="Комментарий",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateField(
                help_text="Укажите дату в формате YYYY:mm:dd",
                verbose_name="Срок выполнения",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="executor",
            field=models.ForeignKey(
                help_text="Подбор сотрудника-исполнителя",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="task_tracker.employee",
                verbose_name="Исполнитель",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="notify_email",
            field=models.BooleanField(default=True, verbose_name="Оповещение по Email"),
        ),
        migrations.AlterField(
            model_name="task",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите родительскую задачу при наличии",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subtasks",
                to="task_tracker.task",
                verbose_name="Родительская задача",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "Ожидает начала"),
                    ("in_progress", "В работе"),
                    ("done", "Выполнена"),
                    ("rework", "На доработке"),
                ],
                default="todo",
                help_text="Отражение статуса выполнения",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
