# Generated by Django 5.2.4 on 2025-08-02 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_tracker", "0002_remove_task_notify_phone_task_difficulty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="parent_task",
            field=models.ForeignKey(
                help_text="Укажите ID родительской задачи, если она есть, по умолчанию отсутствует",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subtasks",
                to="task_tracker.task",
                verbose_name="Родительская задача",
            ),
        ),
    ]
