# Generated by Django 5.2.4 on 2025-08-02 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_tracker", "0003_alter_task_parent_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="competence_level",
        ),
        migrations.RemoveField(
            model_name="task",
            name="difficulty",
        ),
        migrations.AlterField(
            model_name="task",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите ID родительской задачи, если она есть, по умолчанию отсутствует",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subtasks",
                to="task_tracker.task",
                verbose_name="Родительская задача",
            ),
        ),
    ]
