# Generated by Django 5.2.4 on 2025-08-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_tracker", "0004_remove_employee_competence_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="queued",
            field=models.BooleanField(default=False, verbose_name="Очередь назначения"),
        ),
    ]
