# Generated by Django 5.2.4 on 2025-08-03 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_tracker", "0005_task_queued"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="executor",
            field=models.ForeignKey(
                blank=True,
                help_text="Подбор сотрудника-исполнителя",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="task_tracker.employee",
                verbose_name="Исполнитель",
            ),
        ),
    ]
