# Generated by Django 5.2.4 on 2025-08-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_tracker", "0006_alter_task_executor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "Ожидает начала"),
                    ("in_progress", "В работе"),
                    ("done", "Выполнена"),
                ],
                default="todo",
                help_text="Отражение статуса выполнения",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
